# Generated by Django 6.0.3 on 2026-03-29 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(default="Whether you have a project in mind, want to collaborate, or just want to say hello — I'd love to hear from you.", help_text='Intro paragraph on the left side')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True, help_text='Full LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, help_text='Full GitHub profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Full Instagram profile URL')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g. Bachelor of Science in Information Technology', max_length=200)),
                ('school', models.CharField(help_text='School or institution name', max_length=200)),
                ('year_start', models.CharField(help_text='e.g. 2023', max_length=10)),
                ('year_end', models.CharField(blank=True, help_text="e.g. 2027 or leave blank for 'Present'", max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='One goal/drive bullet point', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Goal',
                'verbose_name_plural': 'About Goals',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(help_text='Short tagline shown under your name', max_length=300)),
                ('bio_paragraph1', models.TextField(help_text='First paragraph in the About section')),
                ('bio_paragraph2', models.TextField(blank=True, help_text='Second paragraph (optional)')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('cta_text', models.CharField(default='View My Work', help_text='Button text', max_length=50)),
                ('cta_link', models.CharField(default='/projects/', max_length=100)),
            ],
            options={
                'verbose_name': 'Hero / About Section',
                'verbose_name_plural': 'Hero / About Section',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', models.CharField(help_text='Comma-separated tags e.g. Django, Python, CSS', max_length=300)),
                ('link', models.URLField(blank=True, help_text='Live demo or GitHub URL (optional)')),
                ('link_label', models.CharField(default='View project', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Frontend, Backend, Tools', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Python, Django', max_length=100)),
                ('level', models.PositiveIntegerField(default=70, help_text='Proficiency level 1–100 (shown as bar width %)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='ib_ib.skillcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
