# Generated by Django 6.0.2 on 2026-04-02 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_ib', '0002_alter_skill_options_alter_skillcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='years_of_experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
